api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: "Quizz"
    description: "A Quizz app backend https://github.com/Nykilor/quizz-api"
    version: "1.0"
    show_webby: false
    collection:
        pagination:
            client_items_per_page: true
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
    exception_to_status:
        App\Exception\UserIsBannedException: 403
